export const specialtyToService = {
    "Allergy and Immunology": "Allergy and Immunology",
    "Anesthesiology": "Anesthesiology",
    "Cardiologist": "Cardiology",
    "Cardiothoracic Surgery": "Cardiothoracic Surgery",
    "Clinical Genetics": "Clinical Genetics",
    "Colorectal Surgery": "Colorectal Surgery",
    "Critical Care Medicine": "Critical Care",
    "Dentist": "Dental Care",
    "Dermatologist": "Dermatology",
    "Emergency Medicine": "Emergency Medicine",
    "Endocrinologist": "Endocrinology",
    "Family Medicine": "Family Medicine",
    "Gastroenterologist": "Gastroenterology",
    "General Practitioner": "General Medicine",
    "General Surgery": "General Surgery",
    "Geriatrician": "Geriatric Medicine",
    "Hematologist": "Hematology",
    "Infectious Disease Specialist": "Infectious Disease",
    "Internal Medicine": "Internal Medicine",
    "Interventional Radiologist": "Interventional Radiology",
    "Neonatologist": "Neonatal Care",
    "Nephrologist": "Nephrology",
    "Neurologist": "Neurology",
    "Neurosurgeon": "Neurosurgery",
    "Nuclear Medicine Specialist": "Nuclear Medicine",
    "Obstetrician and Gynecologist": "Obstetrics and Gynecology",
    "Oncologist": "Oncology",
    "Ophthalmologist": "Ophthalmology",
    "Orthopedic Surgeon": "Orthopedic Surgery",
    "Otolaryngologist (ENT)": "ENT and Head & Neck Care",
    "Pain Medicine Specialist": "Pain Management",
    "Pathologist": "Pathology",
    "Pediatrician": "Pediatrics",
    "Physical Medicine and Rehabilitation": "Physical Medicine and Rehabilitation",
    "Plastic Surgeon": "Plastic Surgery",
    "Psychiatrist": "Psychiatry",
    "Pulmonologist": "Pulmonology",
    "Radiologist": "Radiology",
    "Rheumatologist": "Rheumatology",
    "Sleep Medicine Specialist": "Sleep Medicine",
    "Sports Medicine Specialist": "Sports Medicine",
    "Thoracic Surgeon": "Thoracic Surgery",
    "Urologist": "Urology",
    "Vascular Surgeon": "Vascular Surgery",
};