export const STEP_FIELDS = [
  ["name", "email", "password", "phone", "profilePicture"],
  ["specialization", "qualifications", "experience"],
  ["clinicAddress", "bookingPreferences"],
  ["bio", "treatments", "languages"],
  ["socialLinks"],
];

export const BOOKING_OPTIONS = [
  {
    value: "whatsapp",
    label: "WhatsApp",
    description: "Patients book via WhatsApp message",
  },
  {
    value: "bookingForm",
    label: "Booking form",
    description: "Patients use an on-site booking form",
  },
  {
    value: "both",
    label: "Both",
    description: "Offer WhatsApp and a booking form",
  },
];

export const SOCIAL_PLATFORMS = [
  "Facebook",
  "Instagram",
  "LinkedIn",
  "X (Twitter)",
  "YouTube",
  "TikTok",
  "Other",
];

export const MEDICAL_SPECIALTIES = [
  "Allergy and Immunology",
  "Anesthesiology",
  "Cardiologist",
  "Cardiothoracic Surgery",
  "Clinical Genetics",
  "Colorectal Surgery",
  "Critical Care Medicine",
  "Dentist",
  "Dermatologist",
  "Emergency Medicine",
  "Endocrinologist",
  "Family Medicine",
  "Gastroenterologist",
  "General Practitioner",
  "General Surgery",
  "Geriatrician",
  "Hematologist",
  "Infectious Disease Specialist",
  "Internal Medicine",
  "Interventional Radiologist",
  "Neonatologist",
  "Nephrologist",
  "Neurologist",
  "Neurosurgeon",
  "Nuclear Medicine Specialist",
  "Obstetrician and Gynecologist",
  "Oncologist",
  "Ophthalmologist",
  "Orthopedic Surgeon",
  "Otolaryngologist (ENT)",
  "Pain Medicine Specialist",
  "Pathologist",
  "Pediatrician",
  "Physical Medicine and Rehabilitation",
  "Plastic Surgeon",
  "Psychiatrist",
  "Pulmonologist",
  "Radiologist",
  "Rheumatologist",
  "Sleep Medicine Specialist",
  "Sports Medicine Specialist",
  "Thoracic Surgeon",
  "Urologist",
  "Vascular Surgeon",
];

export const VISITING_DAYS = [
  "Sunday",
  "Monday",
  "Tuesday",
  "Wednesday",
  "Thursday",
  "Friday",
  "Saturday",
];
